spring:
  datasource:
    url: jdbc:mysql://spring-deploy.cifqgagtvadq.us-east-2.rds.amazonaws.com/spring_deploy?useUnicode=true&serverTimezone=Asia/Seoul
    username: LJH98
    password: dlalwk123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update