spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot?useUnicode=true&serverTimezone=Asia/Seoul
    username: LJH098
    password: Ekrrdj@159
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update